title: "River's Blog"
baseURL: "https://moon-odyssey.com/"
paginate: 10
theme: papermod
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
enableEmoji: true
keywords: "River, River çš„ä¸ªäººåšå®¢, River's Blog, River Tsui, River Cui, Software Engineer, Software Development, Programming, Tech"

defaultContentLanguage: "zh-cn"
languages:
  zh-cn:
    languageName: "Chinese"
    languageCode: "zh-cn"
    weight: 1
    DateFormat: "2006-01-02"
    menu:
      main:
        - name: "å…³äºŽ"
          identifier: about
          url: /about/
          weight: 1
        - name: "å½’æ¡£"
          url: /archives/
          identifier: archives
          weight: 2
        - name: "æ ‡ç­¾"
          identifier: tags
          url: /tags/
          weight: 3
        - name: "æœç´¢"
          identifier: search
          url: /search/
          weight: 4
  en:
    languageName: "English"
    languageCode: "en-US"
    weight: 2
    DateFormat: "January 2, 2006"
    menu:
      main:
        - name: "About"
          identifier: about
          url: /about/
          weight: 1
        - name: "Archives"
          identifier: archives
          url: /archives/
          weight: 2
        - name: "Tags"
          identifier: tags
          url: /tags/
          weight: 3
        - name: "Search"
          identifier: search
          url: /search/
          weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  homeInfoParams:
    Title: "Hi, I'm River"
    Content: >
      ðŸ‘‹ Welcome to my blog

      - I'm a full-stack software engineer based in Shenzhen, China. I'm passionate about building software that solves real-world problems.

      - Feel free to reach out to me via email at rivertsuiwork@gmail.com or on [GitHub](https://github.com/RiverCui).
  
  socialIcons:
    - name: "GitHub"
      icon: "github"
      url: "https://github.com/RiverCui"
    - name: "Twitter"
      icon: "twitter"
      url: "https://x.com/tree172194471"
    - name: "LinkedIn"
      icon: "linkedin"
      url: "https://www.linkedin.com/in/river-tsui-411aab242"
    - name: "Email"
      icon: "email"
      url: "mailto:rivertsuiwork@gmail.com"
  ShowReadingTime: true
  ShowCodeCopyButtons: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

module:
  hugoVersion:
    extended: false
    min: "0.87.0"
